apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: playlist-service-springboot-native
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: musicstore
    app.kubernetes.io/name: playlist-service-springboot-native
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_NATIVE_IMAGE
        value: "true"
      - name: BP_MAVEN_ADDITIONAL_BUILD_ARGUMENTS
        value: -Pnative
      - name: MANAGEMENT_HEALTH_PROBES_ENABLED
        value: "true"
      - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
        value: "true"
      - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        value: always
      - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
        value: /actuator
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "*"
      - name: MANAGEMENT_SERVER_PORT
        value: "8081"
      - name: SERVER_PORT
        value: "8080"
      - name: SPRING_PROFILES_ACTIVE
        value: postgres
  env:
    - name: MANAGEMENT_HEALTH_PROBES_ENABLED
      value: "true"
    - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
      value: "true"
    - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: always
    - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
      value: /actuator
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: MANAGEMENT_SERVER_PORT
      value: "8081"
    - name: SERVER_PORT
      value: "8080"
    - name: SPRING_PROFILES_ACTIVE
      value: postgres
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: musicstore-classclaim-pgsql
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: scanning_source_policy
      value: scan-policy-java
    - name: scanning_image_policy
      value: scan-policy-java
    - name: gitops_commit_message
      value: playlist-service-springboot native dev supplychain@cluster.local
